In [1]:
# this code is generated by the Domino Code Assist toolbar button
import domino_code_assist as dca
dca.init()

Cannot show ipywidgets in text

# Power Generation in the UK

This app visualizes energy production in the UK by source for the past day and week.

The data is provided by the Balancing Mechanism Reporting Service (BMRS), which provides operational data relating to the GB Electricity Balancing and Settlement arrangements. It is used extensively by market participants to help make trading decisions and understand market dynamics. It acts as a prompt reporting platform as well as a means of accessing historic data.

For more info: https://www.bmreports.com/bmrs/?q=help/about-us

Data is read in each day from BMRS using a scheduled Domino job, and cleaned up and visualized using an app built with Domino's Code Assistant.

In [2]:
import pandas as pd
import os

df = pd.read_csv('/domino/datasets/local/{}/app_data.csv'.format(os.environ.get('DOMINO_PROJECT_NAME')), parse_dates=['datetime'])
df.head()

,HDF,datetime,CCGT,OIL,COAL,NUCLEAR,WIND,PS,NPSHYD,OCGT,OTHER,INTFR,INTIRL,INTNED,INTEW,BIOMASS,INTEM
0,FUELHH,2023-01-01 00:00:00,2973,0,578,5722,11712,0,340,0,145,602,0,0,0,453,252
1,FUELHH,2023-01-01 00:30:00,3282,0,733,5716,11792,0,338,0,153,598,0,0,0,568,252
2,FUELHH,2023-01-01 01:00:00,2941,0,714,5704,12264,0,285,0,225,514,0,0,0,597,254
3,FUELHH,2023-01-01 01:30:00,2744,0,507,5708,12214,0,285,0,198,514,0,0,0,465,254
4,FUELHH,2023-01-01 02:00:00,2720,0,470,5715,11908,0,285,0,158,604,0,0,0,458,252

In [3]:
import datetime
df_today = df.loc[df["datetime"] > (datetime.datetime.today() - datetime.timedelta(days=1)).strftime('%Y-%m-%d %H:%M:%S')]

df_week = df.loc[df["datetime"] > (datetime.datetime.today() - datetime.timedelta(days=7)).strftime('%Y-%m-%d %H:%M:%S')]
df_today.head()

,HDF,datetime,CCGT,OIL,COAL,NUCLEAR,WIND,PS,NPSHYD,OCGT,OTHER,INTFR,INTIRL,INTNED,INTEW,BIOMASS,INTEM
4855,FUELHH,2023-04-12 04:30:00,6392,0,0,4744,11672,0,271,1,94,0,400,0,270,1380,0
4856,FUELHH,2023-04-12 05:00:00,6417,0,0,4743,11214,0,261,1,135,0,338,0,174,1478,0
4857,FUELHH,2023-04-12 05:30:00,7219,0,0,4740,10748,0,261,19,239,0,192,0,162,1484,0
4858,FUELHH,2023-04-12 06:00:00,7914,0,0,4745,10423,0,335,70,347,0,44,330,24,1470,0
4859,FUELHH,2023-04-12 06:30:00,8866,0,0,4738,9960,166,350,69,519,0,0,380,62,1479,0

In [4]:
def vertical_stack(df, columns, index_col, stack_id, value_id):
    df_out = pd.DataFrame(columns=[index_col, stack_id, value_id])
    temp = pd.DataFrame(columns=[index_col, stack_id, value_id])
    
    for c in columns:
        temp[index_col] = df[index_col]
        temp[stack_id] = c
        temp[value_id] = df[c]
        df_out = pd.concat([df_out, temp])
    
    return df_out


columns = ['CCGT', 'OIL', 'COAL', 'NUCLEAR', 'WIND', 'PS', 'NPSHYD', 'OCGT', 'OTHER', 'INTFR', 'INTIRL', 'INTNED', 'INTEW', 'BIOMASS', 'INTEM']
index_col = 'datetime'
stack_id = 'Source'
value_id = 'Production (MW)'

df_today = vertical_stack(df_today, columns, index_col, stack_id, value_id)

df_week = vertical_stack(df_week, columns, index_col, stack_id, value_id)

df_today["datetime"] = df_today["datetime"].astype(str)
df_week["datetime"] = df_week["datetime"].astype(str)

### Production this Week by Source

In [5]:
from solara.express import CrossFilteredFigurePlotly
import plotly.express as px

_base_var_1 = px.area(df_week, x="datetime", y="Production (MW)", template="plotly_dark", color="Source")
_base_var_1.update_layout(margin=dict(l=0, r=0, t=40 if _base_var_1.layout.title.text else 20, b=0))
var_1 = CrossFilteredFigurePlotly(_base_var_1)

var_1

Cannot show ipywidgets in text

### Production Today: All Sources

In [6]:
from solara.express import CrossFilteredFigurePlotly
import plotly.express as px

_base_var_3 = px.area(df_today, x="datetime", y="Production (MW)", color="Source", template="plotly_dark")
_base_var_3.update_layout(margin=dict(l=0, r=0, t=40 if _base_var_3.layout.title.text else 20, b=0))
var_3 = CrossFilteredFigurePlotly(_base_var_3)

var_3

Cannot show ipywidgets in text

In [7]:
# this code is generated by the Domino Code Assist toolbar button
import domino_code_assist as dca
dca.init()

Cannot show ipywidgets in text

In [8]:
from solara import CrossFilterSelect

widget_1 = CrossFilterSelect(df_week, column="Source", configurable=False, multiple=True)
widget_1

Cannot show ipywidgets in text

### Daily Chart Data

### Weekly Chart Data